spring.application.name=ai-application

spring.ai.google.genai.api-key= AIzaSyCb4CnvudI7SRTJ4ISFdlr699F-8Vf-lBU
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
allowed-origin = http://localhost:4200